name: Test runner connection.

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@4
      - name: Print Message
        run: echo "Running on Self-hosted runner."
